### ISSUE TITLE
Delay in streaming video in ios with JWPlayer

### ISSUE THREAD

**Issue by akshada-systematix** [jwplayer/jwplayer-sdk-ios-demo#11]
I have implemented JWPlayer in my xcode project where there are multiple streaming channels. At the first time to stream a new channel it is taking time before like 5-6 seconds and more.

I am not getting any solution on this part.

Please suggest.

**Comment by Daniel-Berger** [comment]
Are your files HLS or MP4. Feel free to send me an email with more info at support+sdk@jwplayer.com. Thanks.
