### ISSUE TITLE
issue with JWPlayerDelegate 

### ISSUE THREAD

**Issue by kilirushi** [jwplayer/jwplayer-sdk-ios-demo#15]
Delagate - (void)onControls:(BOOL)status; not call when action show/hiden control.

**Comment by karimJWP** [comment]
OnControls is fired when controls are enabled or disabled, not when they appear on the screen. Disabling controls means that when the user taps the screen, controls will never appear. We do not have a callback indicating when controls appear or disappear on the screen. For more information on our delegate methods please visit [JWPlayerDelegate Protocol Documentation](https://developer.jwplayer.com/sdk/ios/reference/Protocols/JWPlayerDelegate.html#//api/name/onControls:)
