### ISSUE TITLE
#import <JWPlayer-iOS-SDK/JWPlayerController.h> not found issue.

### ISSUE THREAD

**Issue by Karthikeyan1108** [jwplayer/jwplayer-sdk-ios-demo#16]
I am using xcode 8.1 to run the demo project.It throws an error in Bridging header file.Kindly let me know to fix this.
Language:Swift
![screen shot 2016-11-28 at 7 25 31 pm](https://cloud.githubusercontent.com/assets/16250492/20670758/7847e918-b5a0-11e6-8e65-ec3f1af50b96.png)

**Comment by karimJWP** [comment]
Hi Karthik! Are you using cocoapods? If so, use this import statement: #import <JWPlayer-SDK/JWPlayerController.h>

**Comment by Karthikeyan1108** [comment]
It worked after importing the ios sdk.I thought the Jwdeveloper demo has Framework embedded by default.Guess I was wrong.Thankyou for your Valuable Reply karimJWP .

**Comment by harrisrap** [comment]
I am using cocoa pods, and had this same issue, and used your solution to get past the error in the Bridging header file.
But then I get the same error in ObjCPlayerViewController.m.
I used the same solution to get past the error there.
But now, I get a bunch of Apple Mach-O Linker Errors.

<img width="259" alt="screen shot 2017-05-15 at 1 32 23 pm" src="https://cloud.githubusercontent.com/assets/5605944/26078031/06ce7214-3973-11e7-9eb8-1a8694879b23.png">

**Comment by karimJWP** [comment]
@harrisrap it seems like the framework is being imported multiple times, and the warning indicate the project is searching for the .framework file. Can you verify that you are only importing cocoapods or only importing the .framework ?

**Comment by aadeshmindtickle** [comment]
#import "JWPlayerController.h" inside bridging header file gives error "JWPlayerController.h file not found" I am using CocoaPods for integrating JW player v 3.13; needed help to solve this issue.
Also tried #import <JWPlayer-SDK/JWPlayerController.h> still same error.
Need help!

**Comment by aadeshmindtickle** [comment]
By adding this <#import <JWPlayer_iOS_SDK/JWPlayerController.h>> in bridging header file solved the compiler issue. 
Its a request to JW player documentation team to include this import statement in swift part of documentation as well; I picked it up from objective c documentation(Most ppl skip the objc part of docs if they are using swift).

https://developer.jwplayer.com/jwplayer/docs/ios-configure-your-project
