### ISSUE TITLE
Control icons disappear

### ISSUE THREAD

**Issue by thandang** [jwplayer/jwplayer-sdk-ios-demo#17]
Hi there,

I'm trying to using trial mode to import JW player to my project in swift 2.3 and I saw that all control icons has been disappear (just show missing icon). But when I try to run on demo the icons appear
Both app I use my own hls live stream. Do you know why?

**Comment by karimJWP** [comment]
@thandang what controls are you talking about? The player's controls? The JWPlayerController has a Boolean property called controls. Setting them to false hides the controls.

**Comment by thandang** [comment]
Yes, the player control, I set it to true and the control is shown. But, the problem is the icons such pause/play/loading/expand are missing now. Like this [https://monosnap.com/file/lt005E40KfVhPEgV5MxX6uBoKlb9KO](url)

**Comment by karimJWP** [comment]
I cannot open your URL. What SDK version are you using? If you are offline, the button icons will not load

**Comment by thandang** [comment]
I got it fix. The problem is because of ATS setting which actually skin url is on http. What I solved is just add exception for this url "p.jwpcdn.com". Thank you so much.
