### ISSUE TITLE
Full screen

### ISSUE THREAD

**Issue by codalamanp** [jwplayer/jwplayer-sdk-ios-demo#19]
When I click on fullscreen button it is going to  dismiss the view.

**Comment by karimJWP** [comment]
@codalamanp could you please be more specific ? The view containing the jwplayercontroller is not discarded, it is overlaid by a fullscreen window.

**Comment by codalamanp** [comment]
That was according to my incorrect implementation.
I apologize for that thing.
It is working proper.

Thanks,
Aman Prajapati

**Comment by karimJWP** [comment]
Awesome :)
