### ISSUE TITLE
Cookies 

### ISSUE THREAD

**Issue by codalamanp** [jwplayer/jwplayer-sdk-ios-demo#21]
How can I set cookies for JWPlayer request?

**Comment by karimJWP** [comment]
Hi! The JWConfig has a dictionary property called assetOptions; 
Create a Dictionary containing the cookie as a value and the string 'cookie' as the key. Set that dictionary to assetOptions and call the key AVURLAssetHTTPHeaderFieldsKey.
In Obj-c code, assuming an instance of JWConfig named config:

`config.assetOptions = @{@"AVURLAssetHTTPHeaderFieldsKey": @{@"cookie":  @"theActualCookie"}};`

**Comment by codalamanp** [comment]
Thanks for reply,

What I want is, our web has integrated cloudfront signed cookie where we need to set cookies for cloudfront domain, Is this we can achieve using JW Player in Ios device?

Please refer below URL for more details,

http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-cookies.html

Waiting for your reply
Thanks

**Comment by cvindhani** [comment]
It will be possible by following example,

Objective - C
NSString *cookies = @"cookies1=value;cookies2=value" 
JWConfig *config = [[JWConfig alloc] initWithContentUrl:@"your url"];
config.assetOptions = @{@"AVURLAssetHTTPHeaderFieldsKey":@{@"cookie": cookies}};

Swift
let cookies = "cookies1=value;cookies2=value" 
let config: JWConfig = JWConfig(contentURL: your url)
config.assetOptions = ["AVURLAssetHTTPHeaderFieldsKey":["cookie": cookies]]

Like in cookies NSString you can set all cookies in shown format and you can pass it in JWPlayer's assetOptions like shown above.

**Comment by karimJWP** [comment]
@codalamanp if the suggested solutions did not work, could you please provide a stream and cookies for debugging ? thanks

**Comment by cvindhani** [comment]
I'm unable to provide you stream and cookies but it will definitely work for single and multiple cookies to set on JWPlayer.

**Comment by codalamanp** [comment]
cvindhani it is working for me 
Thanks
