### ISSUE TITLE
Fullscreen Mode Blocked When more than one root UIWindows exist

### ISSUE THREAD

**Issue by vfxdrummer** [jwplayer/jwplayer-sdk-ios-demo#22]
Hey Guys -

First of all, thank you for such a great video player SDK for iOS.
I just wanted to bring to your attention a bug that our team has run into while using the product.
Essentially, we have found that when we have views attached to an additional root UIWindow,
that it blocks the fullscreen mode from happening. It looks like you guys also create an additional root UIWindow for fullscreen mode, so when one already exists, it blocks the functionality.

I have created a version of your sample app which recreates the problem :
https://github.com/vfxdrummer/jwplayer-sdk-ios-demo

You will see that I because I have added an addition UIWindow w/ a transparent view, JWPlayer fails to go into fullscreen mode.

Please let us know your thoughts on this bug.

Thank You,
Tim

**Comment by hblee** [comment]
Hi Tim - just giving you an update that the engineering team will take a look.

**Comment by karimJWP** [comment]
Hi @vfxdrummer , thank you for sharing the demo app. I am getting a lot of Swift Compiler Errors, are you able to build the app ?

**Comment by vfxdrummer** [comment]
I was last time I tried, let me do so again.

**Comment by vfxdrummer** [comment]
I'm so sorry, not all code was committed. Can you do a pull and try it out? Thanks.

**Comment by karimJWP** [comment]
Thanks @vfxdrummer it's building now :)

**Comment by karimJWP** [comment]
@vfxdrummer what is your use case for having multiple windows, and more importantly have a window overlaying the window containing the player ? 
We have logic set-up to prevent fullscreen from triggering when a view is layered on top of the player, because in the past customers complained that a backgrounded player would still go to fullscreen (i.e. upon rotating to landscape if forceFullscreenonLandscape is true) and block the content displayed. If we can get a clear understanding of your use case, we might be able to accommodate both scenarios.

**Comment by vfxdrummer** [comment]
Hey Karim - 

Thanks for responding. Our use case is that a fullscreen semi-transparent overlay is shown when the video is paused. We do this by hooking into an overlayWindow mechanism that uses an additional root UIWindow. Perhaps, if different behavior is desired for Fullscreen mode when additional UIWindows are present, we can have a way to toggle the behavior?

Thoughts on that? Thanks for the reply.

**Comment by vfxdrummer** [comment]
This is from our other developer :

"Our use-cases deal with full-screen overlays that for end-users involve a full-screen resume play overlay, and for development and debugging, diagnostics and other information overlaid on the interface."

**Comment by karimJWP** [comment]
Hi thank you for the response. What is your expected fullscreen behavior when the player is overlaid with another window ? Do you expect the player to still enter fullscreen mode when an overlaying window is present ? Or is the problem simply that when another Window is added to stack, the player has trouble entering and exiting fullscreen properly ?

**Comment by karimJWP** [comment]
Also, out of curiosity, why are you using  UIWindow instead of a UIView to overlay the player when it is paused ?

**Comment by vfxdrummer** [comment]
"What is your expected fullscreen behavior when the player is overlaid with another window ? Do you expect the player to still enter fullscreen mode when an overlaying window is present ?"

Yes. We expect the player to go fullscreen whether or not an existing UIWindow is present.

**Comment by vfxdrummer** [comment]
"Also, out of curiosity, why are you using UIWindow instead of a UIView to overlay the player when it is paused ?"

We have an existing mechanism for full-screen overlays that we use on projects for a variety of purposes, including real-time debugging overlays. It's a convenient hook to add full screen views on top of our app.

**Comment by karimJWP** [comment]
Thank you for the response. Would you expect the fullscreen window to cover your transparent overlay, or would you expect the fullscreen window to be positioned underneath the overlay ?
Also, when your overlay is covering the window containing the player, are touches blocked by your overlay, or are they transferred over to the player ?

**Comment by vfxdrummer** [comment]
Hey Karim -

Sorry for the delay. I've been hyperfocused on a different task the last few days.

Touches are blocked. Our overlay already has a window level that places it above alerts.
So that is higher than the window level that you guys are using.

Does that answer your question? Thanks.

**Comment by hblee** [comment]
Hi Tim,

We've huddled up on this issue and are going to investigate a few options tomorrow. We should have more information for you then on a path forward.

Thanks
Henry

**Comment by vfxdrummer** [comment]
Thanks so much. I appreciate the attentiveness.
Just let us know, thanks!
