### ISSUE TITLE
JWCastController crash

### ISSUE THREAD

**Issue by danipralea** [jwplayer/jwplayer-sdk-ios-demo#25]
Hello I implemented the chromecasting via the JWPlayer framework (via JWCastController) as per 
https://developer.jwplayer.com/sdk/ios/docs/developer-guide/casting/chromecast/

and also 

https://github.com/jwplayer/jwplayer-ios-bestPracticeApps

but I am getting 
```libc++abi.dylib: terminating with uncaught exception of type NSException```

when trying to ```connect``` to a device. No stack trace is generated (even with all the exception breakpoints)

And the code used for connecting:

```swift

    fileprivate var playerController: JWPlayerController!
    fileprivate var castController: JWCastController!

func setup() {
        playerController = JWPlayerController(config: config)
        playerController.delegate = self
        
        // Setup Casting. googleChromeCastVersion = 3.3.0.11401
        castController = JWCastController(player: playerController)
        castController.chromeCastReceiverAppID = kGCKMediaDefaultReceiverApplicationID
        castController.delegate = self
        castController.scanForDevices()
}

public func castButtonTapped(controller: UIViewController) {
        guard let castingDevices = self.castController.availableDevices as? [JWCastingDevice] else {
            logTrace("no casting devices!")
            return
        }
        let alertController = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
        
        if castController.connectedDevice == nil {
            alertController.title = "Cast to"¶
            for device in castingDevices {
                let alertAction = UIAlertAction(title: device.name, style: .default, handler: { [weak self] (action) in
                    guard let `self` = self else { return }
                    self.castController.connect(to: device)
                })
                alertController.addAction(alertAction)
            }
        } else {
            alertController.title = self.castController.connectedDevice.name
            let disconnectAction = UIAlertAction(title: "Disconnect"¶, style: .destructive, handler: { [weak self] (action) in
                guard let `self` = self else { return }
                self.castController.stopCasting()
                self.castController.disconnect()
            })
            alertController.addAction(disconnectAction)
        }
        let cancelAction = UIAlertAction(title: "Cancel"¶, style: .cancel, handler: { _ in })
        alertController.addAction(cancelAction)
        controller.present(alertController, animated: true, completion: nil)
    }
```

**Comment by karimJWP** [comment]
@danipralea what chromecast version are you using? Our SDK is compatible with version 3.3.0.11401

**Comment by karimJWP** [comment]
@danipralea  never mind the previous comment, just saw the comment in the code. DOes it work if you comment out `castController.chromeCastReceiverAppID = kGCKMediaDefaultReceiverApplicationID` ?
If not please contact support at support+sdk@jwplayer.com and they will obtain the necessary info for us to reproduce the bug in our environment.

**Comment by danipralea** [comment]
Hi @karimJWP my version is `3.3.0.11401`

**Comment by karimJWP** [comment]
Hi @danipralea was support able to help?

**Comment by danipralea** [comment]
Hello @karimJWP 
The instructions are not complete. You need to setup the google framework too and do the necessary setup on the google developers console as well

**Comment by karimJWP** [comment]
@danipralea is this to cast to a custom receiver ? WHat setup did you need to do on the 'google developers console' ?

**Comment by danipralea** [comment]
To a standard Google Chromecast device.
I created the receiver media app on developers console and set it up based on their docs in the AppDelegate with that ID. Otherwise it crashes saying that I have not set up the shared cast handler.

**Comment by karimJWP** [comment]
@danipralea there is a misunderstanding here, you do not need to use the GoogleCast API, our player should take care of that for you. Please contact support at support+sdk@jwplayer.com and they will ask you for all the implementation necessary to reproduce on our end. Once we can reproduce we will have a fix for you. Thanks!

**Comment by danipralea** [comment]
I already did that. Apparently I had little feedback from your support team. 
But it's ok now, glad I was able to make it work.
