### ISSUE TITLE
Cocoapods static binaries

### ISSUE THREAD

**Issue by Aximem** [jwplayer/jwplayer-sdk-ios-demo#26]
Hi,

Have you planned to make your POD "dynamic" so we could use it in other pods and not getting : 

`The '***' target has transitive dependencies that include static binaries` 

?

TY

**Comment by karimJWP** [comment]
Hi @Aximem could you please help me understand your use case ? Are you trying to bundle our framework in your own framework ?

**Comment by Aximem** [comment]
Yes in a way, I created my own pod where I use yours, so in my pod podspec I have : 
`s.dependency 'JWPlayer-SDK', '~> 2.0'`

Now if I use my pod in another project I will add it in podfile, I would do : 
- pod install 
And your pod will generate this error because it uses static binaries.

**Comment by okulagin** [comment]
Hi @Aximem ,

Beginning from version 2.8.0 our SDK is dynamic.
Thank you.
