### ISSUE TITLE
#import <JWPlayer-iOS-SDK/JWPlayerController.h> file not found

### ISSUE THREAD

**Issue by tausiq** [jwplayer/jwplayer-sdk-ios-demo#27]
Trying to run the demo. Using Xcode Version 8.3.3 (8E3004b)

Added **JWPlayer-iOS-SDK.framework** manually by following this guide, 
https://developer.jwplayer.com/sdk/ios/docs/developer-guide/intro/getting-started/ 

Build command gives following error, 

> /jwplayer-sdk-ios-demo/JWPlayer-Developer-Demo/JWPlayer-Developer-Demo-Bridging-Header.h:5:9: 'JWPlayer-iOS-SDK/JWPlayerController.h' file not found
> 
> Failed to import bridging header '/jwplayer-sdk-ios-demo/JWPlayer-Developer-Demo/JWPlayer-Developer-Demo-Bridging-Header.h'
> 

![Error screenshot](https://d26dzxoao6i3hh.cloudfront.net/items/2i3D1W161I3C2B2F1E1l/%5Bdd0f7d606bffe8e1497ca014ed33bc48%5D_Image+2017-08-08+at+1.31.05+PM.png?v=d2ba3d02)

**Comment by karimJWP** [comment]
Hi @tausiq what version of the sdk are you using ?

**Comment by tausiq** [comment]
I am using 2.7.6

**Comment by karimJWP** [comment]
@tausiq please contact support+sdk@jwplayer.com and they will help debug this for you, thanks

**Comment by tausiq** [comment]
Contacted with the SDK team. They are very helpful and the issue is resolved. 

I imported **JWPlayer-iOS-SDK.framework** but the actual file was outside the project directory. Copy-paste the **JWPlayer-iOS-SDK.framework** inside your project directory and then import.
