### ISSUE TITLE
HLS stream shows only one subtitle

### ISSUE THREAD

**Issue by orazz** [jwplayer/jwplayer-sdk-ios-demo#28]
HLS stream url. When I click to cc button it doesn't show other languages, how to solve this?

![simulator screen shot aug 30 2017 2 29 01 pm](https://user-images.githubusercontent.com/8214953/29865811-f37659ae-8d8f-11e7-9c67-9de761c699c9.png)

**Comment by karimJWP** [comment]
@orazz what stream are you using ?
