### ISSUE TITLE
-[__NSCFString orientation]: getting crash

### ISSUE THREAD

**Issue by RameshiOS** [jwplayer/jwplayer-sdk-ios-demo#29]
I am getting crash for live streaming.Can you please suggest where I did mistake

       config.file =http://XXX.temp/hls.m3u8
       player = JWPlayerController(config:config)
       config.size = CGSize.init(width: screenSize.width, height: 100)
        player.view.frame = CGRect.init(x: 0, y: 0, width: screenSize.width, height: 100)
        self.view.addSubview(player.view)

Crash showing in log:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString orientation]: unrecognized selector sent to instance 0x608000049750'

**Comment by karimJWP** [comment]
@RameshiOS all changes to the config should be made before instantiating the JWPlayerController. I noticed you set a size to the config after player instantiation. This would not have caused a crash, but it's good to know moving forward :)
