### ISSUE TITLE
Callback for controls hide/show

### ISSUE THREAD

**Issue by naru** [jwplayer/jwplayer-sdk-ios-demo#3]
Would be great if there was a callback for controls hide/show. This way it would be possible to simultaneously update the visibility of related UI elements i.e status bar, custom back button etc.

**Comment by MaxMikheyenko** [comment]
Hey,
sorry for the delay. 
It's on the roadmap, but I can't provide any timeframe at the moment.

**Comment by angusykl** [comment]
Any updates on this?

**Comment by karimJWP** [comment]
No updates on this issue; in the meantime, to programmatically determine if controls are being shown, you can compare the JWPlayerController's safeRegion to its view's frame. The safeRegion is a CGRect indicating the area of the player that is not covered by controls and where therefore it is "safe" to add your own UI elements. If the safe Region's height is smaller than the view's height, than controls are currently being displayed.

**Comment by Arlem** [comment]
Looks like it's now implemented in version 2.6.1! 
https://developer.jwplayer.com/sdk/ios/docs/developer-guide/about/release-notes/

**Comment by karimJWP** [comment]
@naru @Arlem @angusykl, that's right, as of 2.6.1 onControlBarVisible is officially supported :)

**Comment by bluelabeldeveloper1** [comment]
onControlBarVisible is sometime doesnt get call. like when you pause the video, and tap on display screen to hide/show control. onControlBarVisible will not get call. Any idea about that?

**Comment by Allan-Nava** [comment]
Ok Do u have an example?

Inviato da iPhone

**Comment by nhunghuynhthihong** [comment]
I work around by using a bool for this, every call back, this variable will be change

**Comment by Allan-Nava** [comment]
Can you give me a example?
Thanks
