### ISSUE TITLE
iPhone X Full-Screen Cuts Off Controls

### ISSUE THREAD

**Issue by jeremycbutler** [jwplayer/jwplayer-sdk-ios-demo#30]
When I full-screen on an iPhone X it will misplace and cut off the controls at the bottom. If I rotate it back to smaller size and then fullscreen again, the controls are correctly positioned. Any ideas?

![simulator screen shot - iphone x - 2017-09-21 at 11 35 41](https://user-images.githubusercontent.com/7903562/30707417-0bee3a0a-9ec1-11e7-9013-f3a7293ef2ac.png)

**Comment by fresswolf** [comment]
I have this problem when going into fullscreen with forceFullScreenOnLandscape. It doesn't happen when the fullscreen button is touched, even when forceLandscapeOnFullScreen is on.

**Comment by razelkayamdev** [comment]
Experiencing same issue on the latest JW SDK version (2.7.9).

**Comment by karimJWP** [comment]
@fresswolf , @jeremycbutler , @razelkayamdev the issue has been fixed and will ship in our next release, 2.7.10

**Comment by jeremycbutler** [comment]
Awesome. Thanks @karimJWP !

**Comment by karimJWP** [comment]
@fresswolf , @jeremycbutler , @razelkayamdev 2.7.10 released today. Please note that an error prevented release notes from updating on our developer page.
