### ISSUE TITLE
Crash when no networking on real device

### ISSUE THREAD

**Issue by razelkayamdev** [jwplayer/jwplayer-sdk-ios-demo#32]
**Description**: When initialising JWPlayer on a real device, and the device does not have networking (internet is not reachable), the application crashes.

**Reproduction steps**:

1. Download the [JWPlayer developer guide example application](https://github.com/jwplayer/jwplayer-sdk-ios-demo).
2. Add JWPlayer latest SDK (2.7.3+26).
3. Set your device to 'airplane' mode.
4. Install the application on a **real** device, and select the Obj-C, or the Swift implementation.
5. App will crash.

**Crash log**:
[JWPlayer-Developer-Guide  14-11-2017, 9-42.txt](https://github.com/jwplayer/jwplayer-sdk-ios-demo/files/1469933/JWPlayer-Developer-Guide.14-11-2017.9-42.txt)

**Other insights**:
* When example app runs on iPhone8 simulator with Xcode Version 9.1 (9B55), following output is printed to the console: 
> =================================================================
Main Thread Checker: UI API called on a background thread: -[UIApplication statusBarOrientation]
PID: 55370, TID: 2973592, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   JWPlayer-Developer-Guide            0x0000000103d85c36 -[JWRotationHandler initWithPlayerController:] + 279
5   JWPlayer-Developer-Guide            0x0000000103d6b643 __38+[JWPlayerBuilder setUpComponentsFor:]_block_invoke + 62
6   libdispatch.dylib                   0x000000010acbd3f7 _dispatch_call_block_and_release + 12
7   libdispatch.dylib                   0x000000010acbe43c _dispatch_client_callout + 8
8   libdispatch.dylib                   0x000000010acc3352 _dispatch_queue_override_invoke + 1458
9   libdispatch.dylib                   0x000000010acca1f9 _dispatch_root_queue_drain + 772
10  libdispatch.dylib                   0x000000010acc9e97 _dispatch_worker_thread3 + 132
11  libsystem_pthread.dylib             0x000000010b1861ca _pthread_wqthread + 1387
12  libsystem_pthread.dylib             0x000000010b185c4d start_wqthread + 13
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIApplication beginReceivingRemoteControlEvents]
PID: 55370, TID: 2973592, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   JWPlayer-Developer-Guide            0x0000000103d9c19a -[JWLockScreenController setupRemoteCommandCenter] + 1924
5   JWPlayer-Developer-Guide            0x0000000103d9a201 -[JWLockScreenController initWithPlayer:] + 174
6   JWPlayer-Developer-Guide            0x0000000103d943ed -[JWPlayerController setDisplayLockScreenControls:] + 103
7   JWPlayer-Developer-Guide            0x0000000103d6b676 __38+[JWPlayerBuilder setUpComponentsFor:]_block_invoke + 113
8   libdispatch.dylib                   0x000000010acbd3f7 _dispatch_call_block_and_release + 12
9   libdispatch.dylib                   0x000000010acbe43c _dispatch_client_callout + 8
10  libdispatch.dylib                   0x000000010acc3352 _dispatch_queue_override_invoke + 1458
11  libdispatch.dylib                   0x000000010acca1f9 _dispatch_root_queue_drain + 772
12  libdispatch.dylib                   0x000000010acc9e97 _dispatch_worker_thread3 + 132
13  libsystem_pthread.dylib             0x000000010b1861ca _pthread_wqthread + 1387
14  libsystem_pthread.dylib             0x000000010b185c4d start_wqthread + 13

* The following runtime warnings exist in the example project:
<img width="551" alt="screen shot 2017-11-14 at 10 04 48" src="https://user-images.githubusercontent.com/9025189/32769161-6c6c23d8-c923-11e7-946c-68d4053999fb.png">

**Comment by karimJWP** [comment]
This has been fixed in latest version, 2.7.9. Please upgrade
