### ISSUE TITLE
iPhone X landscape seeker bar

### ISSUE THREAD

**Issue by DuboisJoris** [jwplayer/jwplayer-sdk-ios-demo#33]
Hi

When using the iOS JWPlayer SDK (version 2.7.10) in fullscreen mode. The seeker bar is way to close to the home indicator. 

I'm already using the prefersHomeIndicatorAutoHidden & preferredScreenEdgesDeferringSystemGestures API but the swipe gesture is still handled by the system.

**Comment by karimJWP** [comment]
Hi @DuboisJoris could you please share a snapshot?

**Comment by DuboisJoris** [comment]
Hi @karimJWP, here you can see the home indicator (white bar) and the seeking bar of JWPlayer close to each other. When i try to scrub to a different time in the video, the gesture gets recognised by the system and slide trough my apps.

![60d45155-44c8-4a1f-874a-b49e5d902902](https://user-images.githubusercontent.com/7522583/32911839-ab514d94-cb0d-11e7-9014-e40d325bbb33.png)

**Comment by karimJWP** [comment]
@DuboisJoris thanks, I see the issue. As a workaround in the meantime, would setting `timeSliderAbove` in `JWConfig` to `true` help ?

**Comment by DuboisJoris** [comment]
The workaround suggested seems to work OK. The gestures are not interfering with the home indicator anymore. However the Close & Play button are still placed a bit weird around those corners.
![screen shot 2017-11-17 at 11 41 55](https://user-images.githubusercontent.com/7522583/32943418-55f2c132-cb8c-11e7-8b48-cdb41b87928b.png)

**Comment by okulagin** [comment]
@filipchabik112 Hello. What version of SDK do you use?

**Comment by filipchabik112** [comment]
i don't know the exact version of sdk. but i've noticed that it is targeted for iphoneos 10.0

**Comment by okulagin** [comment]
@filipchabik112  Please try the latest SDK version, it is supposed to be fixed there. Otherwise please contact the support team and they will help you!
