### ISSUE TITLE
Apple Mach-O Linker Error

### ISSUE THREAD

**Issue by cesarcarlos75** [jwplayer/jwplayer-sdk-ios-demo#35]
I am working on Xcode 9.2 with Swift 4. I downloaded the JWPlayer-iOS-SDK.framework, added it to the project, and included the -all_load linker flag under Other Linker Flags. 

Everything works fine while testing, but if I try to Archive (Product->Archive) I get an error:

`linker command failed with exit code 1 (use -v to see invocation)`

`Bitcode bundle could not be generated because '/project/path/JWPlayer_iOS_SDK.framework/JWPlayer_iOS_SDK' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/project/path/JWPlayer_iOS_SDK.framework/JWPlayer_iOS_SDK' for architecture arm64`

I have tried cleaning, restarting XCode and restarting the Mac. The error still remains.

How can I get rid of this error? 

Thanks.

**Comment by karimJWP** [comment]
@cesarcarlos75 what version of the SDK are you using ? Have you tried using cocoapods ?

**Comment by cesarcarlos75** [comment]
I'm using version 2.8.2, downloaded from the JW Player Dashboard. I actually tried Cocoapods after posting (v 2.7.11) and didn't get any errors then. Still, would like to know if it's an issue with the framework or something I missed. Thanks.

**Comment by ashishkshaw** [comment]
I am also getting same error

**Comment by okulagin** [comment]
@ashishkshaw which version do you use? Yesterday we have release a version where bitcode issue is addressed.

**Comment by okulagin** [comment]
Please refer to the migration guide (if you used 2.7.x previously) https://developer.jwplayer.com/sdk/ios/docs/developer-guide/troubleshooting/migration/ and ensure to run the script prior submitting your app to app store https://stackoverflow.com/questions/42641806/check-and-remove-unsupported-architecture-x86-64-i386-in-ipa-archive
