### ISSUE TITLE
Orientation Isuue

### ISSUE THREAD

**Issue by bluelabeldeveloper1** [jwplayer/jwplayer-sdk-ios-demo#36]
My App is having only portrait orientation support. When we rotate device to landscape and calling enterFullScreen() method of player, player goes to full screen with landscape left orientation. Not changing to landscape right. What we need to do to support both landscape orientation when player enter in full screen as per device orientation?

Like if device is Landscape Left then player should rotate in landscape left. 
If device is landscape right then player should rotate to landscape right.

**Comment by karimJWP** [comment]
@bluelabeldeveloper1 what is the view controller's supported interface orientation ? Also what orientations do your app support ?

**Comment by bluelabeldeveloper1** [comment]
App is having portrait orientation and player is added as subview in view controller. view controller support  portrait orientation.

**Comment by phanibob7** [comment]
I am also having the same issue

**Comment by fresswolf** [comment]
Same here. It started to happen once I updated from SDK 2.7.10 to the current version 3.0.1.
It was not present in 2.7.10
@coderDove @okulagin any updates on this issue?

**Comment by okulagin** [comment]
@fresswolf not yet, but it is in our backlog. Will update the thread with ETA as soon as we have it. However, thank you for the information regarding 2.7.10

**Comment by karimMourra** [comment]
@bluelabeldeveloper1 please reopen this ticket if the bug still persists

**Comment by AmitaiB** [comment]
For now, you cannot accomplish the behavior you require through global settings; you will need to specify the desired behavior. One way is to permit landscape modes in your project settings, and then have your view controllers [only support portrait mode](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621435-supportedinterfaceorientations#) (possibly made easier by subclassing UIViewController). Another way is to add a flag/toggle in your app delegate, and set your [window's preference](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623107-application#) to that variable.
