### ISSUE TITLE
JWPlayer License Issue

### ISSUE THREAD

**Issue by PradumnaPP** [jwplayer/jwplayer-sdk-ios-demo#38]
I am integrating JWPlayer in iOS application.

It is returning with below error : 
**Error setting up player: Invalid license key**

How I can get a temporary trial license key for JWPlayer. So that I can check the quality of video player and then go for purchase.

If anyone knows the solution to it please let me know.

Thank you.

**Comment by dashtodd** [comment]
@PradumnaPP The only way to get a trial license key is to work with our Sales team to potentially get a trial account. What is the best way for our Sales team to contact you to start the process?
