### ISSUE TITLE
Background Audio Play

### ISSUE THREAD

**Issue by bluelabeldeveloper1** [jwplayer/jwplayer-sdk-ios-demo#39]
We are able to play audio in background mode. But on completion of audio playing, next audio is not getting played automatically. we dont have audios in playlist. we are creating player again on next audio start. Lets take an example

Consider we are having 100 audios to play. Currently 1st one is playing. When oncomplete delegate called by player, we are fetching next audio from array and giving it to player, once we will get “idle”  or “pause” state of player, we are calling player.play() forcefully to auto play. 

This is working as expected when app is open, but not working properly in background mode. sometime player start playing next audio and sometime not.

**Comment by karimJWP** [comment]
@bluelabeldeveloper1 instead of instantiating a new player you could use our [load API ](https://developer.jwplayer.com/sdk/ios/reference/Classes/JWPlayerController.html#//api/name/load:)
you could also set up a playlist

**Comment by bluelabeldeveloper1** [comment]
instead of instantiating a new player you could use our load API 
>> We need to show title and image on lock screen, so we are creating JWPlaylistItem and giving it to player. With loadAPI, How can we use JWPlaylistItem to display detail on lock screen?

Here is some part of our code
var item : JWPlaylistItem = JWPlaylistItem()
item.file      = url
item.title     = title
item.image     = Imageurl
arrPlaylist.add(item)

let config : JWConfig = JWConfig()
config.playlist = arrPlaylist as NSArray as! [JWPlaylistItem]
self.player = JWPlayerController(config: config)

Instead of loadAPI, we tried with loadPlaylist: method and initiating player one time only. but in that case the title and image are not getting changed on lock screen on playing item changed also not able to start next on completion of previous one when phone is locked.

If we create player again for the next item then local file starts playing without any issue. but if we give online media URL then its not working for some of the file type(like working for m3u8 but not working for mp3/mp4). 


Why aren't you using a playlist ?
>> We are having around 360 items. If we give in playlist then there are chances of memory issues  as we are having multiple instance of player globally to keep media playing all over app.

**Comment by karimJWP** [comment]
Hi @bluelabeldeveloper1 thank you for your response. What we will try to fix is ensuring the lockScreen controls are updated when a playlist is loaded as this is a lot more performant than resetting the player every time an item needs to be played. 
Could you please clarify what you meant by `not able to start next on completion of previous one when phone is locked.` - did you mean that loadPlaylist is not getting called ?
Lastly please contact support at support+sdk@jwplayer.com, they will have you reproduce your issue in our demo app; once we have that information we will be able to diagnose. @Daniel-Berger @okulagin be aware of this request

**Comment by bluelabeldeveloper1** [comment]
Could you please clarify what you meant by not able to start next on completion of previous one when phone is locked. - did you mean that loadPlaylist is not getting called ?
--> Consider we are having 500 audio to play. Currently 1st one is playing. When oncomplete delegate called by player, we are fetching next audio from array and initiating player, once we will get “idle” or “pause” state of player, we are calling player.play() forcefully to auto play. But player is not able to start next audio in specific condition when phone is locked.  If Audio files are downloaded and playing from local then its working fine. 

For online media, we are having mp3, mp4 and m3u8 files. We are able to start next audio most of the time if files are m3u8. But not working at all in case of mp3 or mp4

**Comment by bluelabeldeveloper1** [comment]
@karimJWP We have sent you demo app on "support@jwplayer.com" email.

**Comment by Ctulu82** [comment]
@bluelabeldeveloper1 maybe the KeychainAccess issue.
You should check 'kSecAttrAccessibleAfterFirstUnlock' when player communicate with license server.

**Comment by karimMourra** [comment]
@bluelabeldeveloper1 was support able to help you with the issue ? If not please reopen
