### ISSUE TITLE
API Load does not work for 2.8.7+ versions iOS SDK

### ISSUE THREAD

**Issue by marting07** [jwplayer/jwplayer-sdk-ios-demo#41]
Hi, I would like to report an issue of the iOS SDK that happen with the versions 2.8.7 and above (till 2.9.1) related with the "API load" to change the source file for an instantiated player. This behavior was not present a couple of months ago. I have to install the 2.8.6 stable release to be able to load a new source file. Thanks in advance for your time.

**Comment by karimMourra** [comment]
Hi @marting07 in an effort to consolidate our Github Issues and increase response times we are closing this github issues room. From now on we will be using the issues room in our Best Practice App repo (https://github.com/jwplayer/jwplayer-ios-bestPracticeApps) for all issues relating  to the   iOS SDK. If this  issue is still active, please reopen it in https://github.com/jwplayer/jwplayer-ios-bestPracticeApps. If this issue requires urgent attention please visit our  [Support Portal](https://support.jwplayer.com/submit-support-case). Select “I have a question for the technical support team” or “I want to report a bug” and then follow the steps to report your issue. Our support team will follow up in a timely manner.
