### ISSUE TITLE
Add button to control bar in full screen mode

### ISSUE THREAD

**Issue by goodchung** [jwplayer/jwplayer-sdk-ios-demo#42]
I am able to change color of the control bar by editting the "http://p.jwpcdn.com/iOS/Skins/nature01/nature01.css".  However, I would like to add a button in control bar in full screen mode with iOS sdk. Any method I can do it ?

  ```
    config.image = @"/image.jpg";           //title image
    config.title = @"JWPlayer Demo";        // video title
    config.controls = YES;  //default       //show/hide controls
    config.repeat = NO;   //default     //repeat after completion
    config.premiumSkin = JWPremiumSkinRoundster;    //JW premium skin
    config.cssSkin = @"http://p.jwpcdn.com/iOS/Skins/nature01/nature01.css
```
![32943418-55f2c132-cb8c-11e7-8b48-cdb41b87928b](https://user-images.githubusercontent.com/41441320/42978267-99c0adec-8bfe-11e8-8440-fb2003de2d9f.png)

**Comment by ankit0812** [comment]
Any update on this?

**Comment by karimMourra** [comment]
Hi @goodchung and @ankit0812 ! This feature is currently on our roadmap, but not yet scheduled for a specific release. I will update you when it is assigned to a release.
Thanks!

**Comment by karimMourra** [comment]
@goodchung and @ankit0812 this feature was release a while ago. 
An update about this channel: in an effort to consolidate our Github Issues and increase response times we are closing this github issues room. From now on we will be using the issues room in our Best Practice App repo (https://github.com/jwplayer/jwplayer-ios-bestPracticeApps) for all issues relating  to the   iOS SDK. If this  issue is still active, please reopen it in https://github.com/jwplayer/jwplayer-ios-bestPracticeApps. If this issue requires urgent attention please visit our  [Support Portal](https://support.jwplayer.com/submit-support-case). Select “I have a question for the technical support team” or “I want to report a bug” and then follow the steps to report your issue. Our support team will follow up in a timely manner.
