### ISSUE TITLE
Can't change subs in videos with multiple audios in iOs

### ISSUE THREAD

**Issue by ChemaIturbe** [jwplayer/jwplayer-sdk-ios-demo#43]
- Device: iPhone 8+
- iOS Version: 11.4.1
- Olympic Channel App versión: 1.15.0
- iOS SDK 2.9.1
- Language: English
- StreamingUrl: https://vod.olympicchannel.com/NBCR_Production_-_OCS/231/1016/GEPH-ONTHERECS02E012C-_E17101101_master.m3u8
- FilePath: NBCR_Production_-_OCS/231/1016/GEPH-ONTHERECS02E012C-_E17101101_master.m3u8

Steps:
1.- Open OC app
2.- Tap on "Explora" icon at button right menu
3.- Tap on Originals
4.- Scroll down until "Our Originals" section
5.- Tap on "THE OLYMPICS ON THE RECORD" serie
6.- Tap on "Argentina Score Football Perfection in Athens" episode
7.- Observe

![image](https://user-images.githubusercontent.com/41911982/43454934-bc870092-94be-11e8-8f42-9525c1424d42.png)

In iOs app, in the videos with multiaudio only appears the CC button, but not the audio button. When clicking on CC the audio menu appears, but no the subs menú. So we can't change subs.

**Comment by GMSyrimis** [comment]
Hello @ChemaIturbe loading https://vod.olympicchannel.com/NBCR_Production_-_OCS/231/1016/GEPH-ONTHERECS02E012C-_E17101101_master.m3u8 directly into the 2.9.1 JW Player SDK works as expected, with both captions and audiotracks available.

Please reproduce this with the open source demo app this repo provides.

**Comment by ChemaIturbe** [comment]
Hi George, Now the CC into the 2.9.1 JW Player SDK works properly.

Many thanks
Chema

De: George Syrimis <notifications@github.com>
Enviado el: miércoles, 1 de agosto de 2018 16:08
Para: jwplayer/jwplayer-sdk-ios-demo <jwplayer-sdk-ios-demo@noreply.github.com>
CC: Jose Iturbe (UST, ESP) <Jose.Iturbe@ust-global.com>; Mention <mention@noreply.github.com>
Asunto: Re: [jwplayer/jwplayer-sdk-ios-demo] Can't change subs in videos with multiple audios in iOs (#43)


Hello @ChemaIturbe<https://github.com/ChemaIturbe> loading https://vod.olympicchannel.com/NBCR_Production_-_OCS/231/1016/GEPH-ONTHERECS02E012C-_E17101101_master.m3u8 directly into the 2.9.1 JW Player SDK works as expected, with both captions and audiotracks available.

Please reproduce this with the open source demo app this repo provides.
