### ISSUE TITLE
non-commercial version os jwplayer- IOS?

### ISSUE THREAD

**Issue by fukemy** [jwplayer/jwplayer-sdk-ios-demo#44]
hello. How can i find non-commercial version for IOS. like : https://github.com/jwplayer/jwplayer

**Comment by karimJWP** [comment]
We currently do not have an open source project for the iOS SDK. We do however have an open source repo containing best practice examples using our SDK https://github.com/jwplayer/jwplayer-ios-bestPracticeApps
