### ISSUE TITLE
iPhone X hide home indicator on landscape fullscreen of jwplayer

### ISSUE THREAD

**Issue by filipchabik112** [jwplayer/jwplayer-sdk-ios-demo#46]
Hello.
I'm still getting trouble to hide home indicator on fullscreen of jwplayer.
**It is important issue for us.
And we have to solve this problem as soon as possible.**
Please let me know the way to fix this problem.

Until now, to solve this problem i had a debug for jwplayer and noticed the following problems

- on fullscreen mode, there is newer UIWindow for fullscreen of jwplayer.
On my app, UIWindow is always only one. But when i enter the fullscreen mode of jwplayer, i've noticed that there is newer other UIWindow which include the JWFullScreenViewController.

As you know, ios 11 is providing the api to hide home indicator.

_> "prefersHomeIndicatorAutoHidden & preferredScreenEdgesDeferringSystemGestures"_

For my own UIWindow, i can override the above api and hide home indicator on all screen.
But when i enter the fullscreen mode, there is no effect. Because the appeared current screen is JWFullScreenViewController.
So i need to override those 2 api on JWFullScreenViewController to hide home indicator.
But there is no way now.
**Please let me know how can i solve that problem?
This is urgent and important issue for us.**

Thanks.
Regards.

**Comment by filipchabik112** [comment]
Hello.
Is there no any way to solve this problem?

Thanks.
Regards.

**Comment by karimMourra** [comment]
Hi @filipchabik112 in an effort to consolidate our Github Issues and increase response times we are closing this github issues room. From now on we will be using the issues room in our Best Practice App repo (https://github.com/jwplayer/jwplayer-ios-bestPracticeApps) for all issues relating  to the   iOS SDK. If this  issue is still active, please reopen it in https://github.com/jwplayer/jwplayer-ios-bestPracticeApps. If this issue requires urgent attention please visit our  [Support Portal](https://support.jwplayer.com/submit-support-case). Select “I have a question for the technical support team” or “I want to report a bug” and then follow the steps to report your issue. Our support team will follow up in a timely manner.
