### ISSUE TITLE
support rtmp

### ISSUE THREAD

**Issue by fukemy** [jwplayer/jwplayer-sdk-ios-demo#47]
does JWplayer support rtmp? Thanks you

**Comment by karimMourra** [comment]
Hi @fukemy we do not. 

An update on this issue room: in an effort to consolidate our Github Issues and increase response times we are closing this github issues room. From now on we will be using the issues room in our Best Practice App repo (https://github.com/jwplayer/jwplayer-ios-bestPracticeApps) for all issues relating  to the   iOS SDK. If this  issue is still active, please reopen it in https://github.com/jwplayer/jwplayer-ios-bestPracticeApps. If this issue requires urgent attention please visit our  [Support Portal](https://support.jwplayer.com/submit-support-case). Select “I have a question for the technical support team” or “I want to report a bug” and then follow the steps to report your issue. Our support team will follow up in a timely manner.
