### ISSUE TITLE
JWPlayer 3.0 - is there a callback for CC and audio Panel

### ISSUE THREAD

**Issue by Andreoid82** [jwplayer/jwplayer-sdk-ios-demo#48]
With the new 3.* player, when i press the "CC" or the "gear" button is there a way (a callback) to understand that the new panel is shown? 
This panel is a new feature of the new 3.0 version, but i have a custom transparent layer over the player so i need to hide my layer when the jwplayer cc panel is shown and show my layer again after the user changed the cc and jwplayer remove that panel.

Thank you

**Comment by karimMourra** [comment]
Hi Andreoid82, we currently do not plan on supporting this feature.
