### ISSUE TITLE
Add forward 10s button on player

### ISSUE THREAD

**Issue by filipchabik112** [jwplayer/jwplayer-sdk-ios-demo#49]
Hi.
I'm making iphone app which include jwplayer.

The default jwplayer has only backward 10s button now.
But i need also forward 10s button on player.
Please let me know how can i add that button on player.

Thanks.
Regards.

**Comment by ankit0812** [comment]
Ya same here, must have.

**Comment by karimMourra** [comment]
Hi! we currently don't have a `addButton` api, but it's on the roadmap. Said API would allow you to add buttons to the control bar. I will update this issue when a scheduled release is announced

**Comment by ankit0812** [comment]
Please make this soon because every player has this as a must. Move forward or back 10 or 15 secs. (Default iOS Player also)

**Comment by Andy40au** [comment]
@karimMourra any update on this roadmap?

**Comment by ankit0812** [comment]
Any update on this? It is a must have feature!!!

**Comment by karimMourra** [comment]
Hi @Andy40au and @ankit0812 the addButton functionality has been implemented and will ship in our next release, 3.10.0, expected by the end of the month. 
Your button images can be remote or local assets. You can create a button with either the SVG content as a string or the file path of the asset. We highly encourage using the SVG content, since it will inherit the styles of the default buttons in the control bar. Monochromatic, white icons of 24x24 pixels work well.

**Comment by aadeshmindtickle** [comment]
@karimMourra 

I tried adding the JWButton to the control pane but nothing is getting added.
please refer the code below
`if let resourcePath = Bundle.main.resourcePath {
			let imgName = "settingsGear.png"
			let path = resourcePath + "/" + imgName
			let settingsbutton = JWButton(imageUrl: path, accessibilityLabel: "PlayerSettings", cssId: nil, cssClass: nil)
			settingsbutton.delegate = self
			player.add(settingsbutton)
		}`

**Comment by karimMourra** [comment]
Hi @aadeshmindtickle 
Our team cannot investigate this issue without your implementation; I will need you to report a bug via our [Support Portal](https://support.jwplayer.com/submit-support-case). Select “I have a question for the technical support team” or “I want to report a bug” and then follow the steps to report your issue. Our support team will follow up in a timely manner.

**Comment by aadeshmindtickle** [comment]
@karimMourra thanks for reply, I have raised a support ticket.

**Comment by karimMourra** [comment]
Hi all a quick update about this issue room: in an effort to consolidate our Github Issues and increase response times we are closing this github issues room. From now on we will be using the issues room in our Best Practice App repo (https://github.com/jwplayer/jwplayer-ios-bestPracticeApps) for all issues relating  to the   iOS SDK.
