### ISSUE TITLE
Getting error code 100012 on setting up clicking objective c button. What to do to play the ad in this demo app.

### ISSUE THREAD

**Issue by yogesh-finoit** [jwplayer/jwplayer-sdk-ios-demo#50]
[
![simulator screen shot - iphone 7 plus - 2018-11-01 at 16 09 56](https://user-images.githubusercontent.com/12659303/47847276-b7c79500-ddf0-11e8-9bed-dddd6577293c.png)
](url)

**Comment by manveersinghdodiya** [comment]
Hello, I am facing same issue. Kindly provide me solution.

**Comment by karimMourra** [comment]
Per our error documentation, your license key is invalid.
https://developer.jwplayer.com/jw-player/docs/developer-guide/api/errors-reference/#100012

**Comment by manveersinghdodiya** [comment]
Yes after replacing correct license key it works fine. Thanks

**Comment by karimMourra** [comment]
@ThandavaSiva correct. The SDK 3.x uses a different key than 2.x; please contact your sales rep or account manager for your 3.x key.
