### ISSUE TITLE
lock control not appearing in background audio play - iOS 12.2

### ISSUE THREAD

**Issue by bluelabeldeveloper1** [jwplayer/jwplayer-sdk-ios-demo#55]
We are using JWPlayer-SDK (2.8.1) and we are facing one issue with the latest iOS v12.2. 

While listening to audio and the app is backgrounded, lock screen controls aren’t syncing/displaying. e.g. we can’t go to the next audio file unless you open up the app again. 

Its working pretty well for older version of iOS.

Can you look into it and provide your inputs here?

**Comment by karimMourra** [comment]
@bluelabeldeveloper1 what device are you using?

**Comment by duliodenis** [comment]
@karimMourra - we don't think its device specific as we've received reports across all device types - X, 8 Plus, 8, 7, etc.

**Comment by duliodenis** [comment]
@karimMourra - any thoughts?

**Comment by karimMourra** [comment]
@duliodenis @bluelabeldeveloper1 we are working on a solution for this; it will be released with version 3.5.0

**Comment by karimMourra** [comment]
@duliodenis @bluelabeldeveloper1 a fix for this was shipped with version 3.5.0. Please reopen if the issue persists. Thank you!
