### ISSUE TITLE
iOS Duplicate Captions

### ISSUE THREAD

**Issue by dave11mj** [jwplayer/jwplayer-sdk-ios-demo#60]
**Issue**
When adding caption tracks as seen here https://developer.jwplayer.com/sdk/ios/docs/developer-guide/customization/captions/
```
config.tracks = @[[JWTrack trackWithFile:@"/sintel-en.srt" label:@"English" isDefault:YES],
    [JWTrack trackWithFile:@"/sintel-sp.srt" label:@"Spanish"],
    [JWTrack trackWithFile:@"/sintel-ru.srt" label:@"Russian"]];
``` 
If the video file also has `CEA-608 Captions` the player have double captions (iOS built in ones + the JWPlayer captions).

Note that if you remove `config.tracks` JWPlayer will have the CC button and properly hide / show the native captions.

**Expected**
When using `config.tracks` if the `config.file` has `CEA-608 Captions` they are added to the end of the `tracks` array as happens on Android SDK, and Web JWPlayer, so that they player can turn them on / off.

**Sample Screenshot**
![image](https://user-images.githubusercontent.com/6619371/57411886-db630200-71bc-11e9-9851-ddcc13a0dbcf.png)

**Comment by karimMourra** [comment]
@dave11mj thank you for reporting! We will get back to you when a fix is on the way!

**Comment by karimMourra** [comment]
@dave11mj this has been fixed for a while. 

A quick update about this issues  room: in an effort to consolidate our Github Issues and increase response times we are closing this github issues room. From now on we will be using the issues room in our Best Practice App repo (https://github.com/jwplayer/jwplayer-ios-bestPracticeApps) for all issues relating  to the   iOS SDK. If this  issue is still active, please reopen it in https://github.com/jwplayer/jwplayer-ios-bestPracticeApps. If this issue requires urgent attention please visit our  [Support Portal](https://support.jwplayer.com/submit-support-case). Select “I have a question for the technical support team” or “I want to report a bug” and then follow the steps to report your issue. Our support team will follow up in a timely manner.
