### ISSUE TITLE
Callback Event data

### ISSUE THREAD

**Issue by charliefancelli** [jwplayer/jwplayer-sdk-ios-demo#63]
Hi,

Using **Swift**, event callback have an issue to access data.

Example, if we want to have the fullscreen status we need to access to `fullscreen` property.
But this property not exist in `JWEvent`, so we tried to cast in `JWFullscreenEvent` but it's not working.

```
func onFullscreen(_ event: JWEvent!) {
    if let e = event as? JWFullscreenEvent {
      print(e.fullscreen)
    }
  }
````

It's exactly the same issue with all the others event callback (return `JWEvent` or `JWAdEvent`)

Regards,

**Comment by karimMourra** [comment]
@charliefancelli `JWFullscreenEvent` is a protocol, so I believe the proper syntax would be 
```
func onFullscreen(_ event: (JWEvent & JWFullscreenEvent)!) {
      print(event.fullscreen)
  }
```
