### ISSUE TITLE
Quality controls are not accessible?

### ISSUE THREAD

**Issue by ankit0812** [jwplayer/jwplayer-sdk-ios-demo#65]
How to change the quality of a video using the player ? I am only getting the speed options on the settings button.
Also the settings button when tapped takes the complete screen on notch displays and one cannot go back to normal
Landscape works fine.
Portrait covers up the screen
Any help?

![Screenshot 2019-06-14 at 5 19 29 PM](https://user-images.githubusercontent.com/21132111/59507465-bbfc7a80-8ec8-11e9-9ab3-6220bf8bacf3.png)
![Screenshot 2019-06-14 at 5 19 17 PM](https://user-images.githubusercontent.com/21132111/59507466-bc951100-8ec8-11e9-9493-075d5094cb44.png)

**Comment by karimMourra** [comment]
Hi! Thank you for reporting this! We were not aware of the menu being covered by the notch. What version of the SDK are you using ? Is the first picture in portrait fullscreen ? Or are you setting up your player to take up the entire size of the screen ?
With regards to the quality menu, what kind of stream are you using ? For HLS we no longer expose the option to select the quality, since the OS handles automatic quality switching in a more efficient and performant way. If you're using mp4s, you must set up a player with multiple JWSource objects, where each source contains the file of a different quality.
```
JWConfig *config = [JWConfig new];
config.sources = @[[JWSource sourceWithFile:firstMP4url label:firstMP4], [JWSource sourceWithFile:secondMP4url label:secondMP4]];
```

**Comment by ankit0812** [comment]
Thanks, I figured out the source thing.
For the first question : Yes the picture is in portrait full screen and I m setting 
`self.player.view.frame = self.view.frame`

**Comment by asdec** [comment]
Hi Karim, We are using HLS format of video delivery on both Android & IOS. We are getting the quality option in Android SDK by default as per the qualities generated. However, for IOS we are not. Is this a platform specific configuration? If Yes, how can we implement the same on IOS using HLS itself?

**Comment by ankit0812** [comment]
@karimMourra  I have the same issue as @asdec

**Comment by karimMourra** [comment]
Hi @ankit0812, by setting `self.player.view.frame = self.view.frame`, you are not using our fullscreen, therefore it is up to you to ensure that the view does not conflict with the notch. Our fullscreen API should prevent controls from colliding with the notch. please use `self.player.fullscreen = YES`.

**Comment by karimMourra** [comment]
@ankit0812 and @asdec , regarding the multiple qualities for HLS streams, as opposed to Android, we do not expose the different quality options for HLS streams because the OS handles automatic quality switching in a more efficient and performant way.

**Comment by asdec** [comment]
@karimMourra , Does "DASH" protocol support multiple quality streams for both Android and IOS platforms?

**Comment by tumdav** [comment]
> @ankit0812 and @asdec , regarding the multiple qualities for HLS streams, as opposed to Android, we do not expose the different quality options for HLS streams because the OS handles automatic quality switching in a more efficient and performant way.

Is there any solution to show settings ? maybe user wants see another option how can he/she choose it ?

**Comment by karimMourra** [comment]
@tumdav if you want to give the users the option to pick a quality, you can setup a player with multiple mp4 sources. 
```
config.sources = @[
    [JWSource sourceWithFile:@"/example_low.mp4" label:@"180p Streaming" isDefault:YES],
    [JWSource sourceWithFile:@"/example_med.mp4" label:@"270p Streaming"],  
    [JWSource sourceWithFile:@"/example_hi.mp4"  label:@"720p Streaming"]
];
```

**Comment by karimMourra** [comment]
@asdec DASH is currently not supported in iOS. As far as I know, it is not very popular to play dash streams in iOS; even google doesn't use it in iOS

**Comment by tumdav** [comment]
@karimMourra we use hls implementation. manifest files contains full information regarding sources. android and js sdks’ show quality level settings by default but ios sdk does not show

**Comment by CearsKhush** [comment]
@asdec @tumdav @ankit0812 Did you got solution of quality level settings for HLS streams? I am facing the same issue, Please help me with this :)

**Comment by tumdav** [comment]
@CearsKhush on iOS devices it is impossible to have quality control functionality. I found documentation when they explained that the ios system has a better implementation. Frankly speaking, I don't like this idea, but there  is no other solution, so we should accept this solution or try to find alternative player

**Comment by karimMourra** [comment]
@tumdav and @CearsKhush parsing the HLS file into different qualities provides an inferior experience for the viewer. If the HLS master manifest contains metadata such as subtitles or audioTracks, that information is lost when a different quality is manually chosen. Viewers rely on this metadata for accessibility preferences, and users suffering from disabilities depend heavily on them. When you compare our product to alternative players, be sure to verify that their HLS manual quality switching experience does not harm the viewer's experience. 
 If bandwidth consumption is a concern, the `JWConfig` class has a `bitRateUpperBound` property which can be set to cap the maximum bitrate on adaptive streams.
