### ISSUE TITLE
Stop JWPlayer when Screen is being recorded or Screenshot is taken?

### ISSUE THREAD

**Issue by ankit0812** [jwplayer/jwplayer-sdk-ios-demo#66]
I want to stop the JWPlayer when screenshot is taken. After the screenshot is taken we get a notification 'UIApplication.userDidTakeScreenshotNotification'. On this when I am trying to dismiss the controller while the player is in full screen. My method is being called but the player does not get removed.
I have also tried stop() and pause() of JWPlayer before doing this.
Also I tried to remove the JWPlayerView and set it to nil but nothing works.
The controls are gone but the video is still on fullscreen. 
Please do the needful

**Comment by ankit0812** [comment]
If possible provided a method in delegate method that shows Screen is being recorded 
and a method for Screenshot being taken

**Comment by karimMourra** [comment]
Hi Ankit! For this issue I will need you to contact support at support+sdk@jwplayer.com. Your use case should work, but I cannot debug without your implementation. Support will provide you with a very basic app setting up a jwplayer and will ask you to provide the minimal implementation needed to reproduce your issue.
