### ISSUE TITLE
Play/Pause on the player is not working with Bluetooth device in iOS 12 and above

### ISSUE THREAD

**Issue by bluelabeldeveloper1** [jwplayer/jwplayer-sdk-ios-demo#67]
We are using JWPlayer-SDK (2.8.1) and we are facing one issue with the iOS v12 and above

Play/Pause on the player is not working, when we try to play/pause audio or video using Bluetooth device(wireless headphones, AirPods).

Its working pretty well for older version of iOS.

Can you look into it and provide your inputs here?

**Comment by robrowe** [comment]
@bluelabeldeveloper1 we can abandon and close this ticket. we've upgraded to SDK 3.x
