### ISSUE TITLE
Player is not returning proper state on opening app from background mode

### ISSUE THREAD

**Issue by bluelabeldeveloper1** [jwplayer/jwplayer-sdk-ios-demo#70]
Audio is playing in background mode but when I open application from background mode then player is giving "Buffer" state but audio is still playing. so it should give "play" state as we are able to listen the audio.

Now with the player's buffer state putting app in  background mode and opening it again, then player is giving "play" state. this is repeating(if user goes in background from buffer state then on opening app, its showing "play" state, but when from play state then player is giving "buffer" state) But all the time audio is playing.
 
Previously we were using JWPlayer-SDK (2.8.1) and It was working fine but with the SDK 3.6.3, we are having the improper state (Actual audio is playing but receiving buffer state on coming back from background).

**Comment by robrowe** [comment]
@GMSyrimis would you please take a look at this?

**Comment by duliodenis** [comment]
Created Case #00097510 for you with the title "Player is not returning the proper state on opening app from background mode"

**Comment by karimMourra** [comment]
Hi @duliodenis,  @robrowe , @bluelabeldeveloper1 - a quick update on this issues room: in an effort to consolidate our Github Issues and increase response times we are closing this github issues room. From now on we will be using the issues room in our Best Practice App repo (https://github.com/jwplayer/jwplayer-ios-bestPracticeApps) for all issues relating  to the   iOS SDK. If this  issue is still active, please reopen it in https://github.com/jwplayer/jwplayer-ios-bestPracticeApps. If this issue requires urgent attention please visit our  [Support Portal](https://support.jwplayer.com/submit-support-case). Select “I have a question for the technical support team” or “I want to report a bug” and then follow the steps to report your issue. Our support team will follow up in a timely manner.
