### ISSUE TITLE
Crash when pause/play

### ISSUE THREAD

**Issue by PahlevanyanSamvel** [jwplayer/jwplayer-sdk-ios-demo#72]
Please help me 

<img width="975" alt="Screen Shot 2019-10-02 at 7 09 08 PM" src="https://user-images.githubusercontent.com/34054539/66056630-78e21800-e548-11e9-832c-e4e69c5e4ab0.png">

**Comment by karimMourra** [comment]
Hi @PahlevanyanSamvel could you share some reproduction steps ? It sounds like you might be calling `pause` before the player is finished instantiating. It's best practice to use the player's api after the `onReady` callback has fired.

**Comment by PahlevanyanSamvel** [comment]
@karimMourra worked perfectly if the action to use after `onReady` , but it would be nice if not crash.

**Comment by karimMourra** [comment]
@PahlevanyanSamvel Noted! Thank you for the feedback! We will add a ticket in our backlog

**Comment by yogeshpatelios** [comment]
I am facing same issue please help me ? Which method called after onReady ? Thanks
