### ISSUE TITLE
Issue while changing the next play item from lock screen in case of multiple players are initialized

### ISSUE THREAD

**Issue by bluelabeldeveloper1** [jwplayer/jwplayer-sdk-ios-demo#78]
Two-Player has been initialize in the application. Let say one is video and another one is Audio. Both the player is having playlist(let say 10 items). Now video player is paused and Audio player is playing audio. When I lock my screen, the lock control will be shown as the audio is playing. But when I click on the next button from the lock screen, it's changing the next item of both the player. Actually it should only change the item of the audio player.

If I stop the video player instead of pause before locking the screen then it's working fine. but I want both the player and do not want to release or stop any player.

**Comment by bluelabeldeveloper1** [comment]
Any updates here?

**Comment by karimMourra** [comment]
hi @bluelabeldeveloper1 thank you for reporting this. This sounds like an actual bug on our end. I will make a ticket for our PM to review. Thank you!

**Comment by bluelabeldeveloper1** [comment]
Thank you, please keep us updated.

**Comment by bluelabeldeveloper1** [comment]
Any update here?

**Comment by SageBrushes** [comment]
> hi @bluelabeldeveloper1 thank you for reporting this. This sounds like an actual bug on our end. I will make a ticket for our PM to review. Thank you!

@karimMourra can you PM me the ticket for this? @bluelabeldeveloper1 please go through our support team since you are most likely an Enterprise customer. This will be the best and quickest way to get updates and ensure that we're keeping tabs on an issue.

**Comment by karimMourra** [comment]
@SageBrushes the  ticket is SDK-5592
@bluelabeldeveloper1 a fix will ship with 3.15
 An update on this issues room: in an effort to consolidate our Github Issues and increase response times we are closing this github issues room. From now on we will be using the issues room in our Best Practice App repo (https://github.com/jwplayer/jwplayer-ios-bestPracticeApps) for all issues relating  to the   iOS SDK. If this  issue is still active, please reopen it in https://github.com/jwplayer/jwplayer-ios-bestPracticeApps. If this issue requires urgent attention please visit our  [Support Portal](https://support.jwplayer.com/submit-support-case). Select “I have a question for the technical support team” or “I want to report a bug” and then follow the steps to report your issue. Our support team will follow up in a timely manner.
