### ISSUE TITLE
Crash when scrolling collectionViewCell.

### ISSUE THREAD

**Issue by YogeshPateliOS** [jwplayer/jwplayer-sdk-ios-demo#80]
Video is playing all thing is good but the problem is when i scroll my collectionviewcell fast then app crashing and showing this error. This issue mainly comes in iOS 12 devices on iOS 13 it's works fine but it crash randomly when scrolling.
<img width="975" alt="66056630-78e21800-e548-11e9-832c-e4e69c5e4ab0" src="https://user-images.githubusercontent.com/26963737/73249528-0ffb6b80-41db-11ea-8d6e-1b5befcf084d.png">

Please Help me..

**Comment by karimMourra** [comment]
Hi @YogeshPateliOS Our team cannot investigate this issue without your implementation; I will need you to report a bug via our [Support Portal](https://support.jwplayer.com/submit-support-case). Select “I have a question for the technical support team” or “I want to report a bug” and then follow the steps to report your issue. Our support team will follow up in a timely manner.

A quick update on this issues room: in an effort to consolidate our Github Issues and increase response times we are closing this github issues room. From now on we will be using the issues room in our Best Practice App repo (https://github.com/jwplayer/jwplayer-ios-bestPracticeApps) for all issues relating  to the   iOS SDK.
